#!/bin/bash
#
# mailman3:  The GNU Mailing List manager. this init script modified from supervisord's
#
# Author:    Imam Omar Mochtar <iomarmochtar@gmail.com>
#
# chkconfig:    345 50 02
#
# description: The GNU Mailing List manager.


set -a

APP_NAME="mailman3"
BASE_DIR="/opt/mailman3"
PID_FILE="$BASE_DIR/var/master.pid"
MAILMAN="$BASE_DIR/bin/mailman"

# remove this if you manage number of open files in some other fashion
ulimit -n 96000

CUR_DIR=`pwd`
RETVAL=0

# go to working dir
cd $BASE_DIR

running_pid()
{
    # Check if a given process pid's cmdline matches a given name
    pid=$1
    name=$2
    [ -z "$pid" ] && return 1
    [ ! -d /proc/$pid ] && return 1
    (cat /proc/$pid/cmdline | tr "\000" "\n"|grep -q $name) || return 1
    return 0
}

running()
{
# Check if the process is running looking at /proc
# (works for all users)

    # No PID_FILE, probably no daemon present
    [ ! -f "$PID_FILE" ] && return 1
    # Obtain the pid and check it against the binary name
    pid=`cat $PID_FILE`
    running_pid $pid $MAILMAN || return 1
    return 0
}

start() {
        echo "Starting $APP_NAME: "

	OPTIONS=""	
        if [ -e $PID_FILE ]; then 
		if running; then
			echo "ALREADY STARTED"
			return 1
		else
			rm -rf $PID_FILE
			# run force start
			OPTIONS="--force"
		fi
	fi

	# start supervisord with options from sysconfig (stuff like -c)
        $MAILMAN start $OPTIONS
	
	# show initial startup status
	$MAILMAN status
}

stop() {
        echo -n "Stopping $APP_NAME: "
        $MAILMAN stop
}

info() {
        $MAILMAN info
}

restart() {
        stop
        start
}

case "$1" in
    start)
        start
        RETVAL=$?
        ;;
    stop)
        stop
        RETVAL=$?
        ;;
    info)
        info
        RETVAL=$?
        ;;
    restart)
        restart
        RETVAL=$?
        ;;
    status)
	if test -f $PID_FILE; then
		$MAILMAN status
		if running ; then
		    RETVAL=0
		else
		    RETVAL=1
		fi
	else
		echo "$APP_NAME stopped"
	fi
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|info}"
        exit 1
esac

# go back to previous dir
cd $CUR_DIR
exit $RETVAL
